const route = window.RAGBRAI_ROUTE;
const meta = window.RAGBRAI_META;

const startDate = new Date(`${meta.start_date}T00:00:00`);
const today = new Date();
today.setHours(0, 0, 0, 0);
const msPerDay = 24 * 60 * 60 * 1000;
const daysToStart = Math.ceil((startDate - today) / msPerDay);
const RIDE_DAYS = (meta.days && meta.days.length) || 7;
const daysCompleted = daysToStart >= 0 ? 0 : Math.min(RIDE_DAYS, -daysToStart);

// Header miles/climb: finished days' official numbers are the floor; during a
// ride day renderProgressStats() lifts them live using the beacon's projected
// mile (see renderLive). A dead tracker just falls back to the date math.
const dayData = meta.days || [];
const statMilesEl = document.getElementById("stat-miles");
const statClimbEl = document.getElementById("stat-climb");

function sumDays(field, n) {
  return dayData.slice(0, Math.max(0, n)).reduce((s, d) => s + d[field], 0);
}

// Overnight towns bound each ride day, in the same track-mile basis that
// projectOntoTrack() reports (cumulativeMiles is re-marked onto the real
// road line once route.geojson loads).
function dayBoundaryMiles() {
  const b = [0];
  for (let d = 1; d <= RIDE_DAYS; d++) {
    const idx = route.findIndex(p => p.kind === "overnight" && p.day === d);
    b[d] = idx >= 0 ? cumulativeMiles[idx] : b[d - 1];
  }
  return b;
}

function renderProgressStats(liveMile) {
  let miles = sumDays("miles", daysCompleted);
  let climb = sumDays("climb_ft", daysCompleted);
  if (liveMile != null && dayData.length) {
    const b = dayBoundaryMiles();
    let d = 1;
    while (d < RIDE_DAYS && liveMile > b[d]) d++;
    const span = b[d] - b[d - 1];
    const frac = span > 0 ? Math.max(0, Math.min(1, (liveMile - b[d - 1]) / span)) : 0;
    const liveMiles = sumDays("miles", d - 1) + frac * dayData[d - 1].miles;
    if (liveMiles > miles) {
      miles = liveMiles;
      climb = sumDays("climb_ft", d - 1) + frac * dayData[d - 1].climb_ft;
    }
  }
  statMilesEl.textContent = `${miles.toFixed(1)} / ${meta.total_miles.toLocaleString()}`;
  statClimbEl.textContent =
    `${Math.round(climb).toLocaleString()} / ${meta.total_climb_ft.toLocaleString()}`;
}
renderProgressStats(null);
document.getElementById("stat-days").textContent = `${daysCompleted} / ${RIDE_DAYS}`;

const map = L.map("map", { scrollWheelZoom: false });
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  maxZoom: 18,
}).addTo(map);

const latlngs = route.map(p => [p.lat, p.lng]);
const polyline = L.polyline(latlngs, { color: "#1f8f3b", weight: 4, opacity: 0.85 }).addTo(map);
map.fitBounds(polyline.getBounds(), { padding: [30, 30] });

const styleByKind = {
  overnight: { color: "#0a3d62", fill: "#3aa1ff", radius: 8 },
  meeting:   { color: "#7a4a00", fill: "#ffb84d", radius: 6 },
  pass:      { color: "#4a4a4a", fill: "#cfcfcf", radius: 4 },
  special:   { color: "#7a0a4a", fill: "#ff5ec4", radius: 7 },
};

function haversineMiles(a, b) {
  const R = 3958.8;
  const toRad = d => (d * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const h = Math.sin(dLat / 2) ** 2
    + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}
const cumulativeMiles = [];
let _running = 0;
route.forEach((p, i) => {
  if (i > 0) _running += haversineMiles(route[i - 1], p);
  cumulativeMiles[i] = _running;
});

// Detailed road geometry from route.geojson (generated by tools/fetch_routes.py).
// Each feature carries a `variant`: "main" is the primary green line (the route
// we're riding); "gravel", "karras", and "america250" are optional flip-on
// overlays. Until the file loads — or if it's missing — town-to-town straight
// lines stand in.
let trackPts = latlngs;
let trackCum = cumulativeMiles.slice();

// Styling for the optional overlay lines (all off until toggled on).
const OVERLAY_STYLE = {
  gravel:     { color: "#b8860b", weight: 3, opacity: 0.85, dashArray: "3 6" },
  karras:     { color: "#7a0a4a", weight: 3, opacity: 0.9 },
  america250: { color: "#0a5ca8", weight: 3, opacity: 0.9 },
};

// The primary green line is the main routes only, concatenated in ride order.
// This also drives trackPts/trackCum, so live "mile marker" projection stays on
// the route we're actually riding — gravel/specials are just optional detours.
function buildMainLine(mainFeats) {
  const pts = [];
  for (const f of mainFeats) for (const c of f.geometry.coordinates) pts.push([c[1], c[0]]);
  if (!pts.length) return;
  polyline.setLatLngs(pts);
  trackPts = pts;
  trackCum = [0];
  for (let i = 1; i < pts.length; i++) {
    trackCum[i] = trackCum[i - 1] + haversineMiles(
      { lat: pts[i - 1][0], lng: pts[i - 1][1] },
      { lat: pts[i][0], lng: pts[i][1] },
    );
  }
  // Re-mark each town's mile against the real road line (tooltips and the
  // chart read cumulativeMiles lazily, so they pick this up).
  route.forEach((p, i) => { cumulativeMiles[i] = projectOntoTrack(p.lat, p.lng).mile; });
}

// Wire the flip-on toggles in the legend to their Leaflet layer groups. Toggles
// for variants missing from route.geojson stay hidden.
function setupOverlayToggles(overlays) {
  document.querySelectorAll(".route-toggle").forEach(el => {
    const group = overlays[el.dataset.variant];
    const box = el.querySelector("input");
    if (!group) { el.style.display = "none"; return; }
    el.style.display = "inline-flex";
    box.checked = false;
    box.addEventListener("change", () => {
      if (box.checked) group.addTo(map); else map.removeLayer(group);
    });
  });
}

fetch("route.geojson")
  .then(r => { if (!r.ok) throw new Error(r.status); return r.json(); })
  .then(geo => {
    const feats = geo.features.slice().sort((a, b) => a.properties.day - b.properties.day);
    const isMain = f => !f.properties.variant || f.properties.variant === "main";

    buildMainLine(feats.filter(isMain));

    // Group each non-main variant's per-day lines into one toggleable layer.
    const overlays = {};
    for (const f of feats) {
      if (isMain(f)) continue;
      const v = f.properties.variant;
      const style = OVERLAY_STYLE[v] || { color: "#666", weight: 3, opacity: 0.8, dashArray: "3 6" };
      const ll = f.geometry.coordinates.map(c => [c[1], c[0]]);
      const line = L.polyline(ll, style).bindTooltip(
        `${f.properties.label} — Day ${f.properties.day} · ${f.properties.miles} mi`,
        { sticky: true, opacity: 0.95 },
      );
      (overlays[v] = overlays[v] || L.layerGroup()).addLayer(line);
    }
    setupOverlayToggles(overlays);
  })
  .catch(() => {});

const waypointMarkers = [];
route.forEach((p, idx) => {
  const s = styleByKind[p.kind] || styleByKind.pass;
  const m = L.circleMarker([p.lat, p.lng], {
    color: s.color, fillColor: s.fill, fillOpacity: 1, weight: 2, radius: s.radius,
  })
    .addTo(map)
    .bindTooltip(
      () => `<strong>${p.name}</strong><br>Day ${p.day} · ${p.kind}<br>Mile ${cumulativeMiles[idx].toFixed(1)}`,
      { direction: "top", offset: [0, -6], sticky: false, opacity: 0.95 },
    );
  m.on("mouseover", () => syncFromMap(idx));
  m.on("mouseout", () => clearSync());
  waypointMarkers.push(m);
});

const HOVER_RADIUS_BUMP = 4;
function baseRadiusFor(idx) {
  const p = route[idx];
  return (styleByKind[p.kind] || styleByKind.pass).radius;
}
let lastHoverIdx = null;
function showHoverAt(idx) {
  if (!route[idx]) return;
  if (lastHoverIdx !== null && lastHoverIdx !== idx) {
    waypointMarkers[lastHoverIdx]?.setRadius(baseRadiusFor(lastHoverIdx));
    waypointMarkers[lastHoverIdx]?.closeTooltip();
  }
  waypointMarkers[idx]?.setRadius(baseRadiusFor(idx) + HOVER_RADIUS_BUMP);
  waypointMarkers[idx]?.bringToFront();
  waypointMarkers[idx]?.openTooltip();
  lastHoverIdx = idx;
}
function hideHover() {
  if (lastHoverIdx !== null) {
    waypointMarkers[lastHoverIdx]?.setRadius(baseRadiusFor(lastHoverIdx));
    waypointMarkers[lastHoverIdx]?.closeTooltip();
    lastHoverIdx = null;
  }
}

const dayList = document.getElementById("day-list");
function rideDateLabel(dayIndex) {
  const d = new Date(startDate);
  d.setDate(d.getDate() + dayIndex - 1);
  return `${String(d.getMonth() + 1).padStart(2, "0")}/${String(d.getDate()).padStart(2, "0")}`;
}
const dayInfo = meta.days || [];
dayInfo.forEach((d, i) => {
  const li = document.createElement("li");
  const done = d.day <= daysCompleted;
  if (done) li.classList.add("done");
  const leg = i === 0 ? `${d.from} → ${d.to}` : `→ ${d.to}`;
  li.innerHTML = `<input type="checkbox" disabled${done ? " checked" : ""}> <strong>${rideDateLabel(d.day)}</strong> · ${leg} <span class="day-miles">${d.miles.toFixed(1)} mi <span class="day-sep">|</span> ${d.climb_ft.toLocaleString()} ft</span>`;
  dayList.appendChild(li);
});

const statsApi = window.RAGBRAI_CONFIG && window.RAGBRAI_CONFIG.STATS_API;
const milesEl = document.getElementById("training-miles");
const metaEl = document.getElementById("training-meta");
function rideLabel(n) {
  return n === 1 ? "1 ride" : `${(n ?? 0).toLocaleString()} rides`;
}
function animateCount(el, to, durationMs = 1100) {
  const start = performance.now();
  const dot = el.querySelector(".live-dot");
  function tick(now) {
    const t = Math.min(1, (now - start) / durationMs);
    const eased = 1 - Math.pow(1 - t, 3);
    const value = to * eased;
    el.firstChild.nodeValue = (Math.round(value * 10) / 10).toLocaleString();
    if (t < 1) requestAnimationFrame(tick);
  }
  if (dot) el.firstChild.nodeValue = "0";
  requestAnimationFrame(tick);
}
if (statsApi) {
  fetch(`${statsApi}/stats`)
    .then(r => r.json())
    .then(s => {
      animateCount(milesEl, s.total_miles ?? 0);
      metaEl.textContent = `training miles | ${rideLabel(s.ride_count)}`;
    })
    .catch(() => {
      milesEl.firstChild.nodeValue = "—";
      metaEl.textContent = "training miles";
    });
} else {
  milesEl.firstChild.nodeValue = "—";
  metaEl.textContent = "training miles";
}

const countdownEl = document.getElementById("countdown-days");
const countdownMetaEl = document.getElementById("countdown-meta");
if (daysToStart > 0) {
  countdownEl.textContent = daysToStart.toLocaleString();
  countdownMetaEl.textContent = "days to Onawa";
} else if (daysToStart === 0) {
  countdownEl.textContent = "0";
  countdownMetaEl.textContent = "today's the day!";
} else {
  const dayOfRide = Math.min(RIDE_DAYS, 1 - daysToStart);
  countdownEl.textContent = dayOfRide;
  countdownMetaEl.textContent = "day of ride";
}

const canvas = document.getElementById("elevation-chart");
const ctx = canvas.getContext("2d");

// Live rider dot on the elevation profile, drawn at the beacon's projected
// mile and interpolated between the bracketing towns' chart points. Colors
// match the map's .live-marker.
let riderMile = null;
const riderMarkerPlugin = {
  id: "riderMarker",
  afterDatasetsDraw(chart) {
    if (riderMile == null) return;
    const pts = chart.getDatasetMeta(0).data;
    if (pts.length < 2) return;
    let i = 0;
    while (i < cumulativeMiles.length - 2 && cumulativeMiles[i + 1] < riderMile) i++;
    const span = cumulativeMiles[i + 1] - cumulativeMiles[i];
    const t = span > 0 ? Math.max(0, Math.min(1, (riderMile - cumulativeMiles[i]) / span)) : 0;
    const x = pts[i].x + t * (pts[i + 1].x - pts[i].x);
    const y = pts[i].y + t * (pts[i + 1].y - pts[i].y);
    const c = chart.ctx;
    c.save();
    c.beginPath();
    c.arc(x, y, 6, 0, Math.PI * 2);
    c.fillStyle = "#ff3b3b";
    c.fill();
    c.lineWidth = 2;
    c.strokeStyle = "#800000";
    c.stroke();
    c.restore();
  },
};

const elevationChart = new Chart(ctx, {
  type: "line",
  plugins: [riderMarkerPlugin],
  data: {
    labels: route.map(p => p.name),
    datasets: [{
      label: "Elevation",
      data: route.map(p => p.elevation_ft),
      borderColor: "#1f8f3b",
      backgroundColor: "rgba(31, 143, 59, 0.15)",
      fill: true,
      tension: 0.35,
      pointRadius: route.map(p => (styleByKind[p.kind] || styleByKind.pass).radius * 0.6),
      pointHoverRadius: 8,
      pointBackgroundColor: route.map(p => (styleByKind[p.kind] || styleByKind.pass).fill),
      pointBorderColor: route.map(p => (styleByKind[p.kind] || styleByKind.pass).color),
      pointBorderWidth: 2,
    }],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { mode: "index", intersect: false, axis: "x" },
    plugins: {
      legend: { display: false },
      tooltip: {
        callbacks: {
          title: items => route[items[0].dataIndex].name,
          label: ctx => `${ctx.parsed.y.toLocaleString()} ft · Mile ${cumulativeMiles[ctx.dataIndex].toFixed(1)} · Day ${route[ctx.dataIndex].day}`,
        },
      },
    },
    onHover: (_event, elements) => {
      if (elements.length > 0) {
        showHoverAt(elements[0].index);
      } else {
        hideHover();
      }
    },
    scales: {
      x: {
        ticks: {
          autoSkip: false,
          maxRotation: 70,
          minRotation: 60,
          font: { size: 10 },
          // Mobile (<=480px): only show stops that matter — overnight, meeting, special.
          // Desktop: show every town.
          callback: function(_value, index) {
            const p = route[index];
            if (!p) return "";
            if (window.innerWidth <= 480) {
              return (p.kind === "overnight" || p.kind === "meeting" || p.kind === "special") ? p.name : "";
            }
            return p.name;
          },
        },
      },
      y: { title: { display: true, text: "Feet" } },
    },
  },
});
canvas.addEventListener("mouseleave", hideHover);

// --- Live "last seen" location ---
const lastSeenEl = document.getElementById("last-seen");
let liveMarker = null;
let liveTrail = null;

function timeAgo(ts) {
  const mins = Math.round((Date.now() - new Date(ts)) / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins} min ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 36) return `${hrs} hr${hrs === 1 ? "" : "s"} ago`;
  return `${Math.round(hrs / 24)} days ago`;
}

// Project onto the nearest segment of the active track (detailed road line
// when route.geojson is loaded, town-to-town lines otherwise) to estimate
// the mile marker. Equirectangular is plenty accurate at these distances.
function projectOntoTrack(lat, lng) {
  const toRad = d => (d * Math.PI) / 180;
  const cosLat = Math.cos(toRad(lat));
  const px = toRad(lng) * cosLat, py = toRad(lat);
  let best = null;
  for (let i = 0; i < trackPts.length - 1; i++) {
    const ax = toRad(trackPts[i][1]) * cosLat, ay = toRad(trackPts[i][0]);
    const bx = toRad(trackPts[i + 1][1]) * cosLat, by = toRad(trackPts[i + 1][0]);
    const dx = bx - ax, dy = by - ay;
    const len2 = dx * dx + dy * dy;
    const t = len2 ? Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / len2)) : 0;
    const ex = ax + t * dx - px, ey = ay + t * dy - py;
    const dist2 = ex * ex + ey * ey;
    if (!best || dist2 < best.dist2) best = { i, t, dist2 };
  }
  const mile = trackCum[best.i]
    + best.t * (trackCum[best.i + 1] - trackCum[best.i]);
  return { mile };
}

function nearestTown(lat, lng) {
  let best = null;
  for (const p of route) {
    const d = haversineMiles({ lat, lng }, p);
    if (!best || d < best.d) best = { d, name: p.name };
  }
  return best.name;
}

function renderLive(data) {
  const latest = data && data.latest;
  if (!latest || !Number.isFinite(latest.lat) || !Number.isFinite(latest.lng)) return;

  const ll = [latest.lat, latest.lng];
  if (!liveMarker) {
    liveMarker = L.marker(ll, {
      icon: L.divIcon({ className: "live-marker", iconSize: [16, 16] }),
      zIndexOffset: 1000,
    }).addTo(map);
  } else {
    liveMarker.setLatLng(ll);
  }
  liveMarker.bindTooltip(`Last seen ${timeAgo(latest.ts)}`, { direction: "top", offset: [0, -8] });

  const trailPts = (data.trail || []).map(p => [p.lat, p.lng]);
  if (trailPts.length > 1) {
    if (!liveTrail) {
      liveTrail = L.polyline(trailPts, {
        color: "#ff3b3b", weight: 3, opacity: 0.6, dashArray: "1 6",
      }).addTo(map);
    } else {
      liveTrail.setLatLngs(trailPts);
    }
  }

  const pos = projectOntoTrack(latest.lat, latest.lng);
  lastSeenEl.textContent =
    `${timeAgo(latest.ts)} · ~mile ${pos.mile.toFixed(1)}, near ${nearestTown(latest.lat, latest.lng)}`;

  // Feed the live mile into the header stats and the elevation-profile rider
  // dot — only once the ride has started and only while the fix is fresh, so
  // a dead tracker can't paint stale progress.
  const fixAgeMin = (Date.now() - new Date(latest.ts)) / 60000;
  const liveMile = daysToStart <= 0 && fixAgeMin <= 45 ? pos.mile : null;
  renderProgressStats(liveMile);
  updateRiderMarker(liveMile);
}

function updateRiderMarker(mile) {
  if (mile === riderMile) return;
  riderMile = mile;
  elevationChart.update("none");
}

function pollLive() {
  fetch(`${statsApi}/location`)
    .then(r => r.json())
    .then(renderLive)
    .catch(() => {});
}
if (statsApi) {
  pollLive();
  setInterval(pollLive, 60 * 1000);
}

// --- Donate button ---
const donateBtn = document.getElementById("donate-button");
const donateUrl = window.RAGBRAI_CONFIG && window.RAGBRAI_CONFIG.DONATE_URL;
if (donateUrl) {
  donateBtn.href = donateUrl;
} else {
  donateBtn.removeAttribute("href");
  donateBtn.classList.add("disabled");
  donateBtn.textContent = "Donate — link drops soon";
}

// --- Photo strip: six random shots from the shared album ---
const photoStrip = document.getElementById("photo-strip");
if (statsApi && photoStrip) {
  const albumUrl = photoStrip.parentElement.querySelector("a.button").href;
  fetch(`${statsApi}/photos`)
    .then(r => r.json())
    .then(d => {
      const urls = (d.photos || []).slice();
      for (let i = urls.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [urls[i], urls[j]] = [urls[j], urls[i]];
      }
      const picks = urls.slice(0, 6);
      if (picks.length === 0) return;
      photoStrip.replaceChildren(...picks.map(u => {
        const a = document.createElement("a");
        a.href = albumUrl;
        a.target = "_blank";
        a.rel = "noopener noreferrer";
        const img = document.createElement("img");
        // lh3 sizing suffix: 320px square, server-side cropped
        img.src = `${u}=w320-h320-c`;
        img.alt = "Photo from the team album";
        img.loading = "lazy";
        a.append(img);
        return a;
      }));
      photoStrip.hidden = false;
    })
    .catch(() => {});
}

// --- Wall of zingers ---
const cheerWall = document.getElementById("cheer-wall");
const cheerForm = document.getElementById("cheer-form");
const cheerNameEl = document.getElementById("cheer-name");
const cheerMessageEl = document.getElementById("cheer-message");
const cheerCountEl = document.getElementById("cheer-count");
const cheerStatusEl = document.getElementById("cheer-status");
const cheerSubmitEl = document.getElementById("cheer-submit");
const CHEER_MAX = 280;
let wallCheers = [];

// Cheers are user-submitted — build DOM with textContent, never innerHTML.
function renderCheerCard(c) {
  const div = document.createElement("div");
  div.className = "cheer";
  const p = document.createElement("p");
  p.textContent = `“${c.message}”`;
  const footer = document.createElement("footer");
  const who = document.createElement("span");
  who.className = "cheer-who";
  who.textContent = `— ${c.name}`;
  const when = document.createElement("span");
  when.textContent = timeAgo(c.ts);
  footer.append(who, when);
  div.append(p, footer);
  return div;
}

function renderWall() {
  if (wallCheers.length === 0) {
    const empty = document.createElement("p");
    empty.className = "muted small";
    empty.textContent = "No zingers yet — be the first to talk smack.";
    cheerWall.replaceChildren(empty);
    return;
  }
  cheerWall.replaceChildren(...wallCheers.map(renderCheerCard));
}

if (statsApi) {
  fetch(`${statsApi}/cheers`)
    .then(r => r.json())
    .then(d => {
      wallCheers = d.cheers || [];
      renderWall();
    })
    .catch(() => {
      cheerStatusEl.textContent = "Wall's not loading — try a refresh.";
    });
}

cheerNameEl.value = localStorage.getItem("cheer-name") || "";
cheerMessageEl.addEventListener("input", () => {
  cheerCountEl.textContent = CHEER_MAX - cheerMessageEl.value.length;
});

cheerForm.addEventListener("submit", async (e) => {
  e.preventDefault();
  const message = cheerMessageEl.value.trim();
  if (!message || !statsApi) return;
  cheerSubmitEl.disabled = true;
  cheerStatusEl.textContent = "";
  try {
    const res = await fetch(`${statsApi}/cheers`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: cheerNameEl.value.trim(), message }),
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || "Something flatted. Try again.");
    localStorage.setItem("cheer-name", cheerNameEl.value.trim());
    cheerMessageEl.value = "";
    cheerCountEl.textContent = CHEER_MAX;
    wallCheers.unshift(data.cheer);
    renderWall();
    cheerStatusEl.textContent = "Posted. The peloton thanks you.";
  } catch (err) {
    cheerStatusEl.textContent = err.message;
  } finally {
    cheerSubmitEl.disabled = false;
  }
});

function syncFromMap(idx) {
  showHoverAt(idx);
  const meta = elevationChart.getDatasetMeta(0);
  const pt = meta.data[idx];
  const pos = pt ? { x: pt.x, y: pt.y } : { x: 0, y: 0 };
  elevationChart.setActiveElements([{ datasetIndex: 0, index: idx }]);
  elevationChart.tooltip.setActiveElements([{ datasetIndex: 0, index: idx }], pos);
  elevationChart.update();
}
function clearSync() {
  hideHover();
  elevationChart.setActiveElements([]);
  elevationChart.tooltip.setActiveElements([], { x: 0, y: 0 });
  elevationChart.update();
}
